### ISSUE TITLE
Multiple issues when contributing

### ISSUE THREAD

**Issue by 0xR** [ryanflorence/react-project#23]
I wanted to try and add redux to this project, but I'm having a hard time getting up and running.

When I follow the instructions in CONTRIBUTING.md I get this error:

```
Error: Cannot find module 'extract-text-webpack-plugin'
```

This might be due to an OS difference. I am running linux. The error occurs at `somedir/react-project/lib/webpack.client.prod.config.js:11:33`. It makes sense because it would not find `extract-text-webpack-plugin` because it is in `blueprint/node_modules`. I suspect that this dir was normalized by linux from `somedir/react-project/blueprint/node_modules/react-project/lib/start.js:52`.

My current workaround is this:

``` sh
# in blueprint
cd node_modules
rm react-project # if the npm link is still here
git clone git@github.com:ryanflorence/react-project.git
cd ..
npm start
```

This leads to my next error:

```
Error: Cannot find module '../blueprint_package.json'
```

Again this makes sense. This file does not exist. It only exists when I run:

```
somedir/react-project/blueprint/node_modules/react-project> ./scripts/mv-stuff.js
```

Doing that gets webpack to run but it gives me this error:

```
somedir/react-project/blueprint/.build/webpack:/~/react-project/~/utile/lib/index.js:41
      return utile.inflect = require('i')();
             ^
TypeError: Cannot set property inflect of #<Object> which has only a getter

```

For which I don't have a workaround. Which leads me to submit this issue. For now I spend too much time on this.

**Comment by ryanflorence** [comment]
Sorry, developing these kinds of things is always tricky, it's too early for me to spend time trying to make contributing easy in environments other than what I've got. I'll happily merge pull requests that help others though. I hope you can understand.

**Comment by jaredpalmer** [comment]
Try changing your version of node, that fixed this issue for me. Last time I checked, I don't think this repo is working with 5.7.0. I bumped down to 5.0 Should do the trick.
